#!/usr/bin/env python3
"""
Step 3: Generate CLI Tool

This script generates a complete CLI tool from the analysis JSON.
Creates:
- Interactive CLI script
- Core implementation modules
- Cost estimation module
- Documentation
"""

import argparse
import json
import os
import sys
from pathlib import Path


CLI_TEMPLATE = '''#!/usr/bin/env python3
"""
{title} - Interactive CLI

Generated by extract-cli framework
"""

import os
import sys
from typing import Optional

# TODO: Import your implementation modules here


def print_header():
    """Print CLI header."""
    print("""
╔═══════════════════════════════════════════════════════════════╗
║                  {title:^48s}                  ║
║                   Interactive CLI                             ║
╚═══════════════════════════════════════════════════════════════╝
""")


def main():
    """Main CLI entry point."""
    print_header()
    
    print("\\n{core_concept}\\n")
    
    # TODO: Implement CLI workflow based on analysis
    print("User Input Required: {input_required}")
    print("\\nSteps:")
    for i, step in enumerate({steps}, 1):
        print(f"  {{i}}. {{step}}")
    
    print("\\n✅ Configuration ready!")
    return 0


if __name__ == '__main__':
    sys.exit(main())
'''


README_TEMPLATE = '''# {title}

{core_concept}

## Quick Start

```bash
# Install dependencies
pip install -r requirements.txt

# Set API key (if needed)
export OPENROUTER_API_KEY='your-key'

# Run the CLI
python cli.py
```

## User Workflow

**Input Required:** {input_required}

**Steps:**
{steps_list}

**Output:** {output_generated}

## Key Algorithms

{algorithms_list}

## Implementation Notes

{implementation_notes}

## License

MIT License
'''


def generate_cli(analysis: dict, output_dir: str):
    """
    Generate CLI tool from analysis.
    
    Args:
        analysis: Analysis dictionary
        output_dir: Directory to save generated files
    """
    os.makedirs(output_dir, exist_ok=True)
    
    # Generate CLI script
    cli_content = CLI_TEMPLATE.format(
        title=analysis['title'],
        core_concept=analysis['core_concept'],
        input_required=analysis['user_workflow']['input_required'],
        steps=json.dumps(analysis['user_workflow']['steps']),
    )
    
    cli_path = os.path.join(output_dir, 'cli.py')
    with open(cli_path, 'w') as f:
        f.write(cli_content)
    os.chmod(cli_path, 0o755)
    
    print(f"✅ Generated CLI: {cli_path}")
    
    # Generate README
    steps_list = '\n'.join([f"{i}. {step}" for i, step in enumerate(analysis['user_workflow']['steps'], 1)])
    
    algorithms_list = '\n\n'.join([
        f"### {algo['name']}\n\n{algo['description']}\n\n- **Inputs:** {', '.join(algo['inputs'])}\n- **Outputs:** {', '.join(algo['outputs'])}"
        for algo in analysis['key_algorithms']
    ])
    
    implementation_notes = '\n'.join([f"- {note}" for note in analysis['implementation_notes']])
    
    readme_content = README_TEMPLATE.format(
        title=analysis['title'],
        core_concept=analysis['core_concept'],
        input_required=analysis['user_workflow']['input_required'],
        steps_list=steps_list,
        output_generated=analysis['user_workflow']['output_generated'],
        algorithms_list=algorithms_list,
        implementation_notes=implementation_notes
    )
    
    readme_path = os.path.join(output_dir, 'README.md')
    with open(readme_path, 'w') as f:
        f.write(readme_content)
    
    print(f"✅ Generated README: {readme_path}")
    
    # Generate requirements.txt
    requirements = "requests>=2.31.0\n"
    requirements_path = os.path.join(output_dir, 'requirements.txt')
    with open(requirements_path, 'w') as f:
        f.write(requirements)
    
    print(f"✅ Generated requirements.txt: {requirements_path}")


def main():
    parser = argparse.ArgumentParser(
        description='Generate CLI tool from analysis'
    )
    parser.add_argument(
        'analysis_file',
        help='Path to analysis JSON file'
    )
    parser.add_argument(
        '--output-dir',
        default='./generated_cli',
        help='Directory to save generated CLI'
    )
    
    args = parser.parse_args()
    
    # Read analysis
    print(f"Reading analysis from {args.analysis_file}...")
    with open(args.analysis_file, 'r') as f:
        analysis = json.load(f)
    
    # Generate CLI
    print("Generating CLI tool...")
    generate_cli(analysis, args.output_dir)
    
    print("\n✅ CLI tool generated successfully!")
    print(f"\nNext steps:")
    print(f"  1. cd {args.output_dir}")
    print(f"  2. Review and customize the generated files")
    print(f"  3. Implement the core logic based on the analysis")
    print(f"  4. Test the CLI")
    
    return 0


if __name__ == '__main__':
    sys.exit(main())
